#!/bin/bash

init() {
	trash_dir="${XDG_DATA_HOME:-$HOME/.local/share}/trash"

	mkdir -p "$trash_dir"
}

pick() {
	echo $(ls -1r "$trash_dir" | sed "s~$trash_dir/~~" | fzf)
}

delete() {
	file="$1"

	if [[ -z "$file" ]]; then
		file=$(pick)

		[[ -z $file ]] && return
	fi

	trash_file="$trash_dir/$file"

	[[ -d "$trash_file" ]] && rm -Ir "$trash_file" || rm -i "$trash_file"
}

restore() {
	file="$1"

	if [[ -z "$file" ]]; then
		file=$(pick)

		[[ -z $file ]] && return
	fi

	mv "$trash_dir/$file" "./${file#*---}"
}

init

case "$1" in
	-l | "")
		ls -1 "$trash_dir"
	;;
	-d)
		delete $2
	;;
	-r)
		restore $2
	;;
	-p)
		rm -rf "$trash_dir" && mkdir "$trash_dir"
	;;
	-u)
		du -hs "$trash_dir"
	;;
	-h)
		echo "Usage: $(basename $0) [<option>] [file]"
		echo
		echo "Options:"
		echo "  -l  List trashed files (default)"
		echo "  -d  Delete trashed file"
		echo "  -r  Restore trashed file"
		echo "  -p  Purge trash"
		echo "  -u  Show trash usage"
		echo "  -h  Show help"
	;;
	*)
		date=$(date +"%Y-%m-%d-%T---")

		for file in "$@"; do
			mv "$file" "$trash_dir/$date$(basename "$file")"
		done
	;;
esac
