python := "./.venv/bin/python"

setup:
	python -m venv .venv
	{{ python }} -m pip install -r requirements.txt

pip *ARGS:
	{{ python }} -m pip {{ARGS}}
	{{ python }} -m pip freeze > requirements.txt

test *ARGS:
	{{ python }} -m pytest {{ARGS}}

clean:
	rm -rf .pytest_cache .venv */__pycache__

install_dir := env_var_or_default('INSTALL_DIR', env_var('HOME')/'.local/bin')

install:
	cp countdown.py "{{ install_dir }}/countdown"

uninstall:
	rm -f "{{ install_dir }}/countdown"
